# Site settings
title: Jonas Blog
email: jonas28@steps.fm	
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jonas28.github.io/" # the base hostname & protocol for your site
twitter_username: jonas28
github_username:  jonas28

# Build settings
markdown: kramdown
